CREATE POLICY "Allow public read from consents" ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'consents'::"text"));
CREATE POLICY "Allow public upload to consents" ON "storage"."objects" FOR INSERT WITH CHECK (("bucket_id" = 'consents'::"text"));
CREATE POLICY "Authenticated users can delete academy files" ON "storage"."objects" FOR DELETE TO "authenticated" USING (("bucket_id" = 'academy'::"text"));
CREATE POLICY "Authenticated users can delete attachments" ON "storage"."objects" FOR DELETE TO "authenticated" USING (("bucket_id" = 'attachments'::"text"));
CREATE POLICY "Authenticated users can delete clients files" ON "storage"."objects" FOR DELETE TO "authenticated" USING (("bucket_id" = 'clients'::"text"));
CREATE POLICY "Authenticated users can update academy files" ON "storage"."objects" FOR UPDATE TO "authenticated" USING (("bucket_id" = 'academy'::"text"));
CREATE POLICY "Authenticated users can update attachments" ON "storage"."objects" FOR UPDATE TO "authenticated" USING (("bucket_id" = 'attachments'::"text"));
CREATE POLICY "Authenticated users can upload academy files" ON "storage"."objects" FOR INSERT TO "authenticated" WITH CHECK (("bucket_id" = 'academy'::"text"));
CREATE POLICY "Authenticated users can upload attachments" ON "storage"."objects" FOR INSERT TO "authenticated" WITH CHECK (("bucket_id" = 'attachments'::"text"));
CREATE POLICY "Authenticated users can upload client images." ON "storage"."objects" FOR INSERT WITH CHECK ((("bucket_id" = 'clients'::"text") AND ("auth"."role"() = 'authenticated'::"text")));
CREATE POLICY "Authenticated users can upload clients files" ON "storage"."objects" FOR INSERT TO "authenticated" WITH CHECK (("bucket_id" = 'clients'::"text"));
CREATE POLICY "Authenticated users can upload studio images." ON "storage"."objects" FOR INSERT WITH CHECK ((("bucket_id" = 'studios'::"text") AND ("auth"."role"() = 'authenticated'::"text")));
CREATE POLICY "Authenticated users can view academy files" ON "storage"."objects" FOR SELECT TO "authenticated" USING (("bucket_id" = 'academy'::"text"));
CREATE POLICY "Authenticated users can view attachments" ON "storage"."objects" FOR SELECT TO "authenticated" USING (("bucket_id" = 'attachments'::"text"));
CREATE POLICY "Authenticated users can view clients files" ON "storage"."objects" FOR SELECT TO "authenticated" USING (("bucket_id" = 'clients'::"text"));
CREATE POLICY "Avatar insert" ON "storage"."objects" FOR INSERT WITH CHECK (("bucket_id" = 'avatars'::"text"));
CREATE POLICY "Avatar select" ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'avatars'::"text"));
CREATE POLICY "Avatar update" ON "storage"."objects" FOR UPDATE WITH CHECK (("bucket_id" = 'avatars'::"text"));
CREATE POLICY "Client images are publicly accessible." ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'clients'::"text"));
CREATE POLICY "Client insert" ON "storage"."objects" FOR INSERT WITH CHECK ((("bucket_id" = 'clients'::"text") AND ("auth"."role"() = 'authenticated'::"text")));
CREATE POLICY "Client select" ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'clients'::"text"));
CREATE POLICY "Public Read Signatures" ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'consents'::"text"));
CREATE POLICY "Public Upload Signatures" ON "storage"."objects" FOR INSERT WITH CHECK (("bucket_id" = 'consents'::"text"));
CREATE POLICY "Studio images are publicly accessible." ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'studios'::"text"));
CREATE POLICY "Studio insert" ON "storage"."objects" FOR INSERT WITH CHECK ((("bucket_id" = 'studios'::"text") AND ("auth"."role"() = 'authenticated'::"text")));
CREATE POLICY "Studio select" ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'studios'::"text"));
